# Generated by Django 2.0.7 on 2018-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(db_index=True, max_length=20, verbose_name='E-mail')),
                ('comment', models.TextField(db_index=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Сообщения поддержки',
                'verbose_name_plural': 'Сообщение поддержки',
                'ordering': ['name'],
            },
        ),
    ]
