# Generated by Django 2.0.7 on 2018-07-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Фамилия')),
                ('telephone', models.CharField(blank=True, default='380', max_length=12, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-mail')),
                ('time', models.CharField(blank=True, default='Не важно', max_length=30, verbose_name='Удобное время')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказ',
                'ordering': ['email'],
            },
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['email'], 'verbose_name': 'Сообщения поддержки', 'verbose_name_plural': 'Сообщение поддержки'},
        ),
        migrations.AlterField(
            model_name='support',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, verbose_name='E-mail'),
        ),
    ]
