# Generated by Django 2.0.7 on 2018-07-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0003_auto_20180708_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Отправить оповещение вам на почту?'),
        ),
    ]
