# Generated by Django 2.0.7 on 2018-07-06 16:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Описание для контактов',
                'verbose_name_plural': 'Описание для контактов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вопрос/Ответ',
                'verbose_name_plural': 'Вопросы/Ответы',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Описание на главной странице',
                'verbose_name_plural': 'Описание на главной странице',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название типа сайта')),
                ('slug', models.SlugField(help_text='Нужно использовать для создания "хороших" URL-ов', max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена(грн)')),
                ('available', models.BooleanField(default=False, verbose_name='Доступна услуга')),
                ('image', models.ImageField(blank=True, upload_to='products/img/%Y/%m/%d/', verbose_name='Картинка для услуги(300 x 300)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
    ]
