# Generated by Django 2.0.7 on 2018-07-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='section',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название раздела'),
        ),
    ]
